# JaCoCo
# http://www.jacoco.org/jacoco/trunk/doc/maven.html
#
# codacy-coverage-reporter
# https://github.com/codacy/codacy-coverage-reporter
#
# Travis
# https://docs.travis-ci.com/user/customizing-the-build
#
language: java
jdk:
  - oraclejdk7
install: true # Skip the installation step entirely.
              # Note that the install step runs before script step, and with Maven you don't usually need the install step. 
              # Maven will download dependencies on script step anyway.
before_install:
  - sudo apt-get install jq
  # The following command download the 2.0.0 version of "codacy-coverage-reporter" which throws the "NoClassDefFoundError" error when running CodacyCoverageReporter
  # See: https://github.com/codacy/codacy-coverage-reporter
  # - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar -O ~/codacy-coverage-reporter-assembly-latest.jar
script: 
  - mvn -v
  - mvn clean verify
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml --projectToken $CODACY_PROJECT_TOKEN
#
# In alternativa a "codacy-coverage-reporter" è possibile utilizzare il seguente plugin Maven
# See: https://github.com/halkeye/codacy-maven-plugin
# after_success: 
#   - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=./target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN
