package iubar.iva.export;

import java.math.BigDecimal;
import java.util.Date;

public class Data {

    public static void main(String[] args) {
	    Export export = new Export();
	    ///
	    ///
	    int i = 1;
		export.writeField("A", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("IVA17", i);
		i++;
		export.writeField(new BigDecimal("01"), i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("A", i);
		i++;
		export.writeField("\r\n", i);
		i++;
		export.writeField("B", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("Alessandro", i);
		i++;
		export.writeField("Martone", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("12345678901", i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("393273742087", i);
		i++;
		export.writeField("0721805536", i);
		i++;
		export.writeField("Pesaro e Urbino", i);
		i++;
		export.writeField("PU", i);
		i++;
		export.writeField(new Date(926640000L), i);
		i++;
		export.writeField("M", i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("00"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("0"), i);
		i++;
		export.writeField(new Date(958262400L), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Date(958262400L), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Date(958262400L), i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField(new Date(958262400L), i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField(new Date(1493942400L), i);
		i++;
		export.writeField(Boolean.FALSE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField(Boolean.TRUE, i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("A", i);
		i++;
		export.writeField("\r\n", i);
		i++;
		export.writeField("D", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("ASDFGHJKLMNBVCXZ", i);
		i++;			//Inizio non posizionali
		i++;
		i++;
		export.writeField(Boolean.TRUE, export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField("12345678910", export.getFieldToString(i));
		i++;
		export.writeField("1", export.getFieldToString(i));
		i++;
		i++;
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField("12345678910", export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new Date(1451692800L), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("10000"), export.getFieldToString(i));
		i++;///////////////////////////////////////////////////////////////////
		i++;
		i++;		//22
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 100;  	//VB, VC (da riga 23, da riga 51), (122)
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(Boolean.TRUE, export.getFieldToString(i));
		i++;	//VD (132)
		i++;
		i++;	//133
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 40;
		i += 40;	//213
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;		//219 dopo di questa inizia VE
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 22;
		i += 8;		//249
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;		//254
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 6;
		i += 3;
		i += 14;	//277
		i++;		//dopo questo inizia VF	
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 26;
		i += 11;	//315
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 10;	//329
		i++;
		export.writeField(Boolean.TRUE, export.getFieldToString(i));
		i += 7;
		i += 12;	//349
		i++;
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 23;	//377
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(Boolean.TRUE, export.getFieldToString(i));
		i += 4;		//388
		i++;		//Dopo di questa inizia VG
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 55;	//444
		i++; 		//Inizio VH
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;		//VH
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 2;
		i += 53;	//VJ inizia a 497 , (533)
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 12;	//VI inizia a 536 , (546)
		i++;		//VK 547
		export.writeField("12345678901", export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("13"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1001"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1000"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;		//557
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 9;		//(565)
        i++;		//566
        export.writeField(Boolean.TRUE, export.getFieldToString(i));
        i += 20;	//VN inizia a 567 , (586)
        i++;		//VL (587)
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 4;
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 7;
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 16;
        i++;		//V1, Dopo inizia VX
        export.writeField("VAVCVDVEVFVHVJVKVLVX", export.getFieldToString(i));
        i += 15;
        i++;
        export.writeField(Boolean.TRUE, export.getFieldToString(i));
        i += 3;		//Dopo inizia V0, (640)
        i += 117;	//757
        i++;		//VT 758
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 44;
        i += 222; 	//1027
		i++;		//1028
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField("", i - 1152 + 124);
		i++;
		export.writeField("A", i - 1152 + 124);
		i++;
		export.writeField("\r\n", i - 1152 + 124);
		i++;
		export.writeField("Z", i - 1152 + 124);
		i++;
		export.writeField("", i - 1152 + 124);
		i++;
		export.writeField("1", i - 1152 + 124);
		i++;
		export.writeField("1", i - 1152 + 124);
		i++;
		export.writeField("", i - 1152 + 124);
		i++;
		export.writeField("A", i - 1152 + 124);
		i++;
		export.writeField("\r\n", i - 1152 + 124);
		export.writeOnFile();
    }
}
