		/*i++;
		export.writeField("A", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("IVA17", i);
		i++;
		export.writeField(new BigDecimal("01"), i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("A", i);
		i++;
		export.writeField("\r\n", i);
		i++;
		export.writeField("B", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("Alessandro", i);
		i++;
		export.writeField("Martone", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("12345678901", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("393273742087"), i);
		i++;
		export.writeField(new BigDecimal("0721805536"), i);
		i++;
		export.writeField("Pesaro e Urbino", i);
		i++;
		export.writeField("PU", i);
		i++;
		export.writeField(new Data(926640000L), i);
		i++;
		export.writeField("M", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Boolean(), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("00"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField(new Data(1493942400L), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("A", i);
		i++;
		export.writeField("\r\n", i);
		i++;
		export.writeField("D", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		i++;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal(""), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal(""), export.getFieldToString(i));
		i++;
		export.writeField("1", export.getFieldToString(i));
		i++;
		i++;
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new Date(1451692800L), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("10000"), export.getFieldToString(i));
		i++;///////////////////////////////////////////////////////////////////
		i++;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 103;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 40;
		i += 40;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 22;
		i += 8;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 6;
		i += 3;
		i += 14;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 26;
		i += 11;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 10;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i += 7;
		i += 12;
		i++;
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 24;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i += 4;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 36;
		i += 27;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 15;
		


*/
package iubar.iva.export;

import java.math.BigDecimal;

public class Data {

	public static void main(String[] args) {
	    Export export = new Export();
        export.writeField("A", 1);
        export.writeField("IVA17", 3);
        export.writeField(Boolean.TRUE, export.getFieldToString(127));
        export.writeField(new BigDecimal(""), export.getFieldToString(128));
    }
}
