		/*i++;
		export.writeField("A", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("IVA17", i);
		i++;
		export.writeField(new BigDecimal("01"), i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("A", i);
		i++;
		export.writeField("\r\n", i);
		i++;
		export.writeField("B", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("Alessandro", i);
		i++;
		export.writeField("Martone", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("12345678901", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("393273742087"), i);
		i++;
		export.writeField(new BigDecimal("0721805536"), i);
		i++;
		export.writeField("Pesaro e Urbino", i);
		i++;
		export.writeField("PU", i);
		i++;
		export.writeField(new Data(926640000L), i);
		i++;
		export.writeField("M", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Boolean(), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("00"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField(new BigDecimal(""), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField(new Data(0L), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField(new Data(1493942400L), i);
		i++;
		export.writeField(new Boolean(false), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField(new Boolean(true), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("A", i);
		i++;
		export.writeField("\r\n", i);
		i++;
		export.writeField("D", i);
		i++;
		export.writeField("RSSDRL96F57I967O", i);
		i++;
		export.writeField(new BigDecimal("1"), i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("", i);
		i++;
		export.writeField("ASDFGHJKLMNBVCXZ", i);
		i++;			//Inizio non posizionali
		i++;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal(""), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal(""), export.getFieldToString(i));
		i++;
		export.writeField("1", export.getFieldToString(i));
		i++;
		i++;
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField("", export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal(""), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new Date(1451692800L), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("10000"), export.getFieldToString(i));
		i++;///////////////////////////////////////////////////////////////////
		i++;
		i++;		//22
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 100;  	//VB, VC (da riga 23, da riga 51), (122)
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i++;	//VD (132)
		i++;
		i++;	//133
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 40;
		i += 40;	//213
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;		//219 dopo di questa inizia VE
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 22;
		i += 8;		//249
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;		//254
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 6;
		i += 3;
		i += 14;	//277
		i++;		//dopo questo inizia VF	
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 26;
		i += 11;	//315
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 10;	//329
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i += 7;
		i += 12;	//349
		i++;
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 24;	//377
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new Boolean(true), export.getFieldToString(i));
		i += 4;		//389
		i++;		//Dopo di questa inizia VG, VH inizia a 446
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 55;	//445
		i++; 		//Inizio VH
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;		//VH
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i += 77;	//VJ inizia a 497 , (534)
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 12;	//VI inizia a 536 , (547)
		i++;		//VK 548
		export.writeField(new BigDecimal("12345678901"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("13"), export.getFieldToString(i));
		i++;
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1001"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1000"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;
		export.writeField(new BigDecimal("1"), export.getFieldToString(i));
		i++;		//557
		export.writeField(new BigDecimal("0"), export.getFieldToString(i));
		i += 9;		//(566)
        i++;		//567
        export.writeField(new Boolean(true), export.getFieldToString(i));
        i += 20;	//VN inizia a 568 , (587)
        i++;		//VL (588)
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 4;
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 7;
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 16;
        i++;		//Dopo inizia VX
        export.writeField("VAVCVDVEVFVHVJVKVLVX", export.getFieldToString(i));
        i += 15;
        i++;
        export.writeField(new Boolean(true), export.getFieldToString(i));
        i += 3;		//Dopo inizia V0, (641)
        i += 117;	//758
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i++;
        export.writeField(new BigDecimal("0"), export.getFieldToString(i));
        i += 46;
        i += 222;
		i++;
		export.writeField("", export.getFieldToString(i));
		




*/
package iubar.iva.export;

import java.math.BigDecimal;

public class Data {

	public static void main(String[] args) {
	    Export export = new Export();
        export.writeField("A", 1);
        export.writeField("IVA17", 3);
        export.writeField(Boolean.TRUE, export.getFieldToString(127));
        export.writeField(new BigDecimal(""), export.getFieldToString(128));
    }
}
